name: Build MacOS
# This is a workflow specifically for Intel macOS.
# This workflow has last been updated to work for Wireshark 4.0.5 and is currently not being used.
# Modifications to this file will be needed to get it working with later versions of Wireshark.
on:
  workflow_call:
    inputs:
      MAJOR_VERSION:
        description: "Version string for wireshark tag needed to build can be v#.#.# or v#.#.#-rc#"
        type: string
        required: true
        default: "4"
      MINOR_VERSION:
        description: "Minor version of the wireshark tag"
        type: string
        required: true
        default: "0"
      PATCH_VERSION:
        description: "Patch version of the wireshark tag"
        type: string
        required: true
        default: "5"

jobs:
  macos:
    name: Build on MacOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout Wireshark
        uses: actions/checkout@v4
        with:
          repository: wireshark/wireshark
          path: "./wireshark"
          ref: v${{ inputs.MAJOR_VERSION }}.${{ inputs.MINOR_VERSION }}.${{ inputs.PATCH_VERSION }}
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install deps
        continue-on-error: true
        run: |
          brew install opus c-ares glib libgcrypt gnutls lua cmake python nghttp2 snappy lz4 libxml2 ninja \
            libmaxminddb libsmi spandsp brotli minizip zstd libssh libilbc speexdsp gettext pcre2 "$@"

          # install qt5
          brew install qt@5
          qt5_dir="$(brew --prefix)/opt/qt@5/lib/cmake/Qt5:/usr/local/Cellar/qt@5/5.15.12:/usr/local/Cellar/qt@5/5.15.12/lib/cmake/Qt5:/usr/local/opt/qt@5/bin"
          echo "Qt5_DIR=$qt5_dir" >> $GITHUB_ENV

      - name: Link SMF plugin
        shell: bash
        run: |
          ln -s ${{ github.workspace }}/src/CMakeListsCustom.txt  ${{ github.workspace }}/wireshark/CMakeListsCustom.txt
          ln -s ${{ github.workspace }}/src/smf  ${{ github.workspace }}/wireshark/plugins/epan/smf

      - name: Mkdir
        run: mkdir build

      - name: Cmake
        working-directory: build
        env:
          CMAKE_PREFIX_PATH: ${{ env.Qt5_DIR }}
          Qt5_DIR: ${{ env.Qt5_DIR }}
          PKG_CONFIG_PATH: ${{ env.Qt5_DIR }}/lib/pkgconfig
        run: |
          cmake -GNinja  ${{ github.workspace }}/wireshark \
            -D CMAKE_PREFIX_PATH=${{ env.Qt5_DIR }} \
            -D Qt5_DIR=${{ env.Qt5_DIR }} \
            -D Qt5Core_DIR=${{ env.Qt5_DIR }} \
            -DPython_ROOT_DIR=${{ env.pythonLocation }} \
            -DPython_LIBRARY=${{ env.pythonLocation }}/lib \
            -DPython_INCLUDE_DIR=${{ env.pythonLocation }}/include \
            -DPython_EXECUTABLE=${{ env.pythonLocation }}/bin/python \
            -DPython_FIND_STRATEGY=LOCATION \
            -DCMAKE_POLICY_DEFAULT_CMP0094=NEW

      - name: Build
        run: ninja
        working-directory: build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wireshark-smf-macos
          path: ${{ github.workspace }}/build/run/Wireshark.app/Contents/PlugIns/wireshark/**/epan/smf.so
